openapi: 3.0.3
info:
  title: Neutale Audiobook Platform - Admin API
  description: API specification for administrative operations and system management.
  version: 4.1.1
  contact:
    name: Neutale API Support
    email: support@neutale.com
  license:
    name: Proprietary
servers:
  - url: https://audiobook-dev.sunny250486.workers.dev
    description: Development environment
  - url: https://audiobook-prod.sunny250486.workers.dev
    description: Production environment
components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          description: Health status of the API
          example: ok
        timestamp:
          type: string
          description: ISO 8601 timestamp of the health check
          example: 2025-09-16T12:00:00.000Z
        version:
          type: string
          description: Current API version
          example: 4.1.1
        environment:
          type: string
          description: Current environment (development, production, etc.)
          example: development
      required:
        - status
        - timestamp
        - version
  parameters: {}
security:
  - bearerAuth: []
tags:
  - name: Admin
    description: Admin related operations
  - name: System
    description: System related operations
  - name: Migration
    description: Migration related operations
  - name: Debug
    description: Debug related operations
paths:
  /api/health:
    get:
      tags:
        - System
      summary: Health check endpoint
      description: Returns the current health status of the API
      responses:
        "200":
          description: Health status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
