openapi: 3.0.3
info:
  title: Neutale Audiobook Platform - StoryGen API
  description: API specification for StoryGen integration and content import.
  version: 4.1.1
  contact:
    name: Neutale API Support
    email: support@neutale.com
  license:
    name: Proprietary
servers:
  - url: https://audiobook-dev.sunny250486.workers.dev
    description: Development environment
  - url: https://audiobook-prod.sunny250486.workers.dev
    description: Production environment
components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          description: Health status of the API
          example: ok
        timestamp:
          type: string
          description: ISO 8601 timestamp of the health check
          example: 2025-09-16T12:00:00.000Z
        version:
          type: string
          description: Current API version
          example: 4.1.1
        environment:
          type: string
          description: Current environment (development, production, etc.)
          example: development
      required:
        - status
        - timestamp
        - version
    InitUploadResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        story_id:
          type: string
          description: Generated story ID
          example: story_abc123
        language_group_id:
          type: string
          description: Language group ID for translations
          example: group_xyz789
        assets:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              upload_url:
                type: string
                format: uri
              status:
                type: string
                enum:
                  - pending
                  - uploading
                  - completed
            required:
              - id
              - status
          description: Asset upload information
      required:
        - success
        - story_id
        - language_group_id
        - assets
    ContentBlock:
      type: object
      properties:
        id:
          type: string
          description: Block ID
          example: block_123
        type:
          type: string
          enum:
            - text
            - paragraph
            - heading_1
            - heading_2
            - heading_3
            - image
            - image_placeholder
            - quote
            - audio
          description: Content block type
          example: paragraph
        order:
          type: number
          description: Block order within chapter
          example: 1
        content:
          type: object
          additionalProperties:
            nullable: true
          description: Block content data
          example:
            text: Once upon a time...
        metadata:
          type: object
          additionalProperties:
            nullable: true
          description: Additional block metadata
      required:
        - id
        - type
        - order
        - content
    Chapter:
      type: object
      properties:
        id:
          type: string
          description: Chapter ID
          example: chapter_123
        title:
          type: string
          description: Chapter title
          example: The Beginning
        chapterNumber:
          type: number
          description: Chapter number
          example: 1
        blocks:
          type: array
          items:
            $ref: "#/components/schemas/ContentBlock"
          description: Content blocks in this chapter
        duration:
          type: number
          description: Chapter duration in seconds
          example: 1800
        audioUrl:
          type: string
          description: Chapter audio URL
          example: https://example.com/audio/chapter1.mp3
      required:
        - id
        - title
        - chapterNumber
        - blocks
    AssetManifest:
      type: object
      properties:
        id:
          type: string
          description: Asset ID
          example: asset_123
        filename:
          type: string
          description: Asset filename
          example: cover.jpg
        type:
          type: string
          enum:
            - image
            - audio
            - video
            - document
          description: Asset type
          example: image
        category:
          type: string
          enum:
            - cover
            - thumbnail
            - chapter
            - scene
            - character
          description: Asset category
          example: cover
        expectedSize:
          type: number
          minimum: 0
          exclusiveMinimum: true
          description: Expected file size in bytes
          example: 1048576
        description:
          type: string
          description: Asset description
          example: Story cover image
        placement:
          type: string
          enum:
            - inline
            - background
            - overlay
          description: Asset placement
          example: inline
        metadata:
          type: object
          additionalProperties:
            nullable: true
          description: Additional asset metadata
      required:
        - id
        - filename
        - type
        - expectedSize
    StoryInitRequest:
      type: object
      properties:
        metadata:
          type: object
          properties:
            title:
              type: string
              description: Story title
              example: The Adventure Begins
            author:
              type: string
              default: AI Story Generator
              description: Story author
              example: Jane Doe
            description:
              type: string
              description: Story description
              example: An exciting tale of adventure and discovery
            genre:
              type: string
              description: Story genre
              example: Fantasy
            tags:
              type: array
              items:
                type: string
              description: Story tags
              example:
                - adventure
                - fantasy
                - magic
            language:
              type: string
              minLength: 1
              description: Story language code
              example: en
            originLanguage:
              type: string
              description: Original language for translations
              example: en
            languageGroupId:
              type: string
              description: Language group ID for translations
              example: group_abc123
            chapters:
              type: array
              items:
                $ref: "#/components/schemas/Chapter"
              description: Story chapters with content blocks
            styleGuide:
              type: object
              properties:
                theme:
                  type: string
                  description: Visual theme
                  example: dark fantasy
                colorPalette:
                  type: array
                  items:
                    type: string
                  description: Color palette
                  example:
                    - "#2D3748"
                    - "#4A5568"
                    - "#718096"
                imageStyle:
                  type: string
                  description: Image style preference
                  example: realistic
                mood:
                  type: string
                  description: Story mood
                  example: mysterious
            review:
              type: object
              properties:
                overall_rating:
                  type: number
                  description: Overall quality rating
                  example: 4.5
                verdict:
                  type: string
                  description: Review verdict
                  example: High quality story with engaging plot
                final_rating:
                  type: number
                  description: Final quality rating
                  example: 4.2
                quality_achieved:
                  type: boolean
                  description: Whether quality standards were achieved
                  example: true
              required:
                - overall_rating
                - verdict
                - final_rating
                - quality_achieved
          required:
            - title
            - language
            - chapters
        assets:
          type: array
          items:
            $ref: "#/components/schemas/AssetManifest"
          description: Asset manifest for all story assets
        totalExpectedSize:
          type: number
          description: Total expected size of all assets in bytes
          example: 10485760
      required:
        - metadata
        - assets
    UploadStatus:
      type: object
      properties:
        story_id:
          type: string
          description: Story ID
          example: story_abc123
        status:
          type: string
          enum:
            - initialized
            - uploading_assets
            - uploading_content
            - finalizing
            - completed
            - failed
          description: Upload status
          example: uploading_assets
        progress:
          type: number
          minimum: 0
          maximum: 1
          description: Upload progress (0.0-1.0)
          example: 0.75
        assets_uploaded:
          type: integer
          description: Number of assets uploaded
          example: 5
        total_assets:
          type: integer
          description: Total number of assets
          example: 8
        content_uploaded:
          type: boolean
          description: Whether content has been uploaded
          example: true
        error_message:
          type: string
          description: Error message if upload failed
          example: Asset upload failed
        created_at:
          type: string
          description: Upload creation timestamp
          example: 2025-09-16T12:00:00Z
        updated_at:
          type: string
          description: Last update timestamp
          example: 2025-09-16T12:30:00Z
      required:
        - story_id
        - status
        - progress
        - assets_uploaded
        - total_assets
        - content_uploaded
        - created_at
        - updated_at
    FinalizeUploadResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        story_id:
          type: string
          example: story_abc123
        status:
          type: string
          enum:
            - published
            - draft
          example: published
        published_at:
          type: string
          description: Publication timestamp if published
          example: 2025-09-16T12:00:00Z
      required:
        - success
        - story_id
        - status
  parameters: {}
security:
  - bearerAuth: []
tags:
  - name: StoryGen
    description: StoryGen related operations
  - name: Import
    description: Import related operations
  - name: Upload
    description: Upload related operations
  - name: Content
    description: Content related operations
paths:
  /api/health:
    get:
      tags:
        - System
      summary: Health check endpoint
      description: Returns the current health status of the API
      responses:
        "200":
          description: Health status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
  /api/progressive-upload/init:
    post:
      tags:
        - StoryGen
      summary: Initialize story upload
      description: Initialize a new progressive story upload with metadata and asset manifest
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StoryInitRequest"
      responses:
        "201":
          description: Upload initialized successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InitUploadResponse"
        "400":
          description: Invalid request data
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid story metadata
                required:
                  - error
        "401":
          description: Unauthorized - invalid API key
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid API key
                required:
                  - error
  /api/progressive-upload/{storyId}/status:
    get:
      tags:
        - StoryGen
      summary: Get upload status
      description: Get the current status of a progressive upload
      security:
        - bearerAuth: []
      parameters:
        - schema:
            type: string
            description: Story ID
            example: story_abc123
          required: true
          name: storyId
          in: path
      responses:
        "200":
          description: Upload status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadStatus"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid API key
                required:
                  - error
        "404":
          description: Upload not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Upload not found
                required:
                  - error
  /api/progressive-upload/{storyId}/finalize:
    post:
      tags:
        - StoryGen
      summary: Finalize story upload
      description: Complete the progressive upload and publish the story
      security:
        - bearerAuth: []
      parameters:
        - schema:
            type: string
            description: Story ID
            example: story_abc123
          required: true
          name: storyId
          in: path
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                publish:
                  type: boolean
                  default: true
                  description: Whether to publish the story immediately
                  example: true
      responses:
        "200":
          description: Upload finalized successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FinalizeUploadResponse"
        "400":
          description: Upload not ready for finalization
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Upload not complete
                required:
                  - error
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid API key
                required:
                  - error
        "404":
          description: Upload not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Upload not found
                required:
                  - error
